version: '3'
services:
  frontend:
    build:
      context: ./angular-app
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./springboot
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
